/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vistas;

import java.awt.Color;

/**
 *
 * @author Angel FV
 */
public class JDialogNoDisponible extends javax.swing.JDialog {

    /**
     * Creates new form JDialogNoDisponible
     */
    public JDialogNoDisponible(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        /*
        getContentPane().setBackground(Color.YELLOW);
        */
        getContentPane().setBackground(new Color(255, 255, 204));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAdvertencia = new javax.swing.JLabel();
        txtAdvertencia = new javax.swing.JTextArea();
        btnAdvertencia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblAdvertencia.setBackground(new java.awt.Color(255, 255, 204));
        lblAdvertencia.setForeground(new java.awt.Color(255, 153, 51));
        lblAdvertencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Advertencia.png"))); // NOI18N

        txtAdvertencia.setEditable(false);
        txtAdvertencia.setBackground(new java.awt.Color(255, 255, 204));
        txtAdvertencia.setColumns(20);
        txtAdvertencia.setFont(new java.awt.Font("Microsoft JhengHei UI", 3, 14)); // NOI18N
        txtAdvertencia.setForeground(new java.awt.Color(255, 153, 51));
        txtAdvertencia.setText("Opción temporalmente no disponible\n          Disculpe las molestias!!");
        txtAdvertencia.setBorder(null);

        btnAdvertencia.setBackground(new java.awt.Color(255, 153, 0));
        btnAdvertencia.setForeground(new java.awt.Color(255, 255, 255));
        btnAdvertencia.setText("ACEPTAR");
        btnAdvertencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdvertenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblAdvertencia, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtAdvertencia, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdvertencia)
                .addGap(150, 150, 150))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAdvertencia)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtAdvertencia, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addGap(56, 56, 56)
                .addComponent(btnAdvertencia)
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdvertenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdvertenciaActionPerformed

    }//GEN-LAST:event_btnAdvertenciaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAdvertencia;
    private javax.swing.JLabel lblAdvertencia;
    private javax.swing.JTextArea txtAdvertencia;
    // End of variables declaration//GEN-END:variables
}
