/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vistas;

import java.awt.Color;
import java.awt.Component;
import java.awt.event.ItemEvent;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import javax.swing.UIManager;

/**
 *
 * @author Angel FV
 */
public class JDialogAltaReserva extends javax.swing.JDialog {

    /**
     * Creates new form AltaReserva
     */
    public JDialogAltaReserva(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        // Eliminar el título del marco del JDialog       
        Color backgroundColor = new Color(250, 250, 230);  //blanco roto
        
    // Establecer el color de fondo gris oscuro para los botones
        Color darkGrayBackground = Color.DARK_GRAY;
        
        this.getContentPane().setBackground(backgroundColor);
        initComponents();
        
        pnlPersonaContacto.setBackground(backgroundColor);
        pnlDatosEvento.setBackground(backgroundColor);
        /*
        pnlDatosEventoFechaAsistentes.setBackground(backgroundColor);
        pnlDatosEventoTipo.setBackground(backgroundColor);
        pnlDatosEventoCocina.setBackground(backgroundColor);
        */
        
        for (Component comp : pnlDatosEvento.getComponents()) {
            if (comp instanceof JButton) {
                comp.setBackground(darkGrayBackground);
                comp.setForeground(Color.WHITE); // Cambiar el color del texto si lo deseas
            }else{
                comp.setBackground(backgroundColor);
            }
        }
        
        for (Component comp : pnlDatosEventoTipo.getComponents()) {
            comp.setBackground(backgroundColor);
        }
        
        for (Component comp : pnlDatosEventoCocina.getComponents()) {
            comp.setBackground(backgroundColor);
        }
        
         // Establecer el tooltip deseado
        dateChooserFecha.setToolTipText("Seleccione una fecha");

        // Asegurar que el JTextField interno también tiene el mismo tooltip
        if (dateChooserFecha.getDateEditor() instanceof JComponent) {
            ((JComponent) dateChooserFecha.getDateEditor()).setToolTipText("Seleccione una fecha");
        }
        
        // Personalizar el color de fondo y texto de los tooltips
        UIManager.put("ToolTip.background", new Color(255, 255, 204)); // Fondo amarillo claro
        UIManager.put("ToolTip.foreground", Color.BLACK); // Texto negro
        UIManager.put("ToolTip.border", BorderFactory.createLineBorder(Color.GRAY)); // Bordes opcionales
        
        
        spinnerNumeroJornadas.setVisible(false);
        lblNumeroJornadas.setVisible(false);
        chkBRequiereHabitaciones.setVisible(false);
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTipoEvento = new javax.swing.ButtonGroup();
        buttonGroupCocina = new javax.swing.ButtonGroup();
        pnlPersonaContacto = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        pnlDatosEvento = new javax.swing.JPanel();
        pnlDatosEventoFechaAsistentes = new javax.swing.JPanel();
        dateChooserFecha = new com.toedter.calendar.JDateChooser();
        txtNumeroAsistentes = new javax.swing.JTextField();
        lblNumeroAsistentes = new javax.swing.JLabel();
        pnlDatosEventoTipo = new javax.swing.JPanel();
        rBtnBanquete = new javax.swing.JRadioButton();
        rBtnJornada = new javax.swing.JRadioButton();
        rBtnCongreso = new javax.swing.JRadioButton();
        spinnerNumeroJornadas = new javax.swing.JSpinner();
        lblNumeroJornadas = new javax.swing.JLabel();
        chkBRequiereHabitaciones = new javax.swing.JCheckBox();
        pnlDatosEventoCocina = new javax.swing.JPanel();
        rbnCarta = new javax.swing.JRadioButton();
        rbnBufe = new javax.swing.JRadioButton();
        rbnCitaChef = new javax.swing.JRadioButton();
        rbnNoPrecisa = new javax.swing.JRadioButton();
        btnReservar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnReservarSinCierre = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlPersonaContacto.setBorder(javax.swing.BorderFactory.createTitledBorder("Persona de contacto"));

        lblNombre.setText("Nombre");

        txtNombre.setToolTipText("Nombre de la persona de contacto");
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        lblTelefono.setText("Telefono");

        txtTelefono.setToolTipText("numero de telefono persona de contacto");
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPersonaContactoLayout = new javax.swing.GroupLayout(pnlPersonaContacto);
        pnlPersonaContacto.setLayout(pnlPersonaContactoLayout);
        pnlPersonaContactoLayout.setHorizontalGroup(
            pnlPersonaContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPersonaContactoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        pnlPersonaContactoLayout.setVerticalGroup(
            pnlPersonaContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPersonaContactoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPersonaContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPersonaContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTelefono)
                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPersonaContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNombre)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pnlDatosEvento.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Evento"));

        pnlDatosEventoFechaAsistentes.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha y asistentes"));

        dateChooserFecha.setToolTipText("fecha posterior al dia actual");

        txtNumeroAsistentes.setToolTipText("numero de asistentes obligatorio");
        txtNumeroAsistentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroAsistentesActionPerformed(evt);
            }
        });

        lblNumeroAsistentes.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNumeroAsistentes.setText("Numero ");

        javax.swing.GroupLayout pnlDatosEventoFechaAsistentesLayout = new javax.swing.GroupLayout(pnlDatosEventoFechaAsistentes);
        pnlDatosEventoFechaAsistentes.setLayout(pnlDatosEventoFechaAsistentesLayout);
        pnlDatosEventoFechaAsistentesLayout.setHorizontalGroup(
            pnlDatosEventoFechaAsistentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosEventoFechaAsistentesLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(dateChooserFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(lblNumeroAsistentes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumeroAsistentes, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144))
        );
        pnlDatosEventoFechaAsistentesLayout.setVerticalGroup(
            pnlDatosEventoFechaAsistentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosEventoFechaAsistentesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosEventoFechaAsistentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlDatosEventoFechaAsistentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNumeroAsistentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNumeroAsistentes))
                    .addComponent(dateChooserFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlDatosEventoTipo.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo"));
        pnlDatosEventoTipo.setMinimumSize(new java.awt.Dimension(472, 100));
        pnlDatosEventoTipo.setName(""); // NOI18N

        buttonGroupTipoEvento.add(rBtnBanquete);
        rBtnBanquete.setText("Banquete");
        rBtnBanquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnBanqueteActionPerformed(evt);
            }
        });

        buttonGroupTipoEvento.add(rBtnJornada);
        rBtnJornada.setText("Jornada");
        rBtnJornada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnJornadaActionPerformed(evt);
            }
        });

        buttonGroupTipoEvento.add(rBtnCongreso);
        rBtnCongreso.setText("Congreso");
        rBtnCongreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnCongresoActionPerformed(evt);
            }
        });

        spinnerNumeroJornadas.setToolTipText("numero de dias duracion");

        lblNumeroJornadas.setText("Numero Jornadas ");

        chkBRequiereHabitaciones.setText("Requiere Habitaciones");
        chkBRequiereHabitaciones.setToolTipText("marque en caso de querer reservar habitaciones para los asistentes");
        chkBRequiereHabitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBRequiereHabitacionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDatosEventoTipoLayout = new javax.swing.GroupLayout(pnlDatosEventoTipo);
        pnlDatosEventoTipo.setLayout(pnlDatosEventoTipoLayout);
        pnlDatosEventoTipoLayout.setHorizontalGroup(
            pnlDatosEventoTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosEventoTipoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlDatosEventoTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosEventoTipoLayout.createSequentialGroup()
                        .addGroup(pnlDatosEventoTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rBtnJornada)
                            .addComponent(rBtnCongreso))
                        .addGap(35, 35, 35)
                        .addComponent(spinnerNumeroJornadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rBtnBanquete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNumeroJornadas, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkBRequiereHabitaciones)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDatosEventoTipoLayout.setVerticalGroup(
            pnlDatosEventoTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosEventoTipoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rBtnBanquete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rBtnJornada)
                .addGap(6, 6, 6)
                .addGroup(pnlDatosEventoTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(rBtnCongreso)
                    .addComponent(spinnerNumeroJornadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumeroJornadas)
                    .addComponent(chkBRequiereHabitaciones))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pnlDatosEventoCocina.setBorder(javax.swing.BorderFactory.createTitledBorder("Cocina"));

        buttonGroupCocina.add(rbnCarta);
        rbnCarta.setText("Carta");

        buttonGroupCocina.add(rbnBufe);
        rbnBufe.setText("Bufé");
        rbnBufe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnBufeActionPerformed(evt);
            }
        });

        buttonGroupCocina.add(rbnCitaChef);
        rbnCitaChef.setText("Pedir cita chef");
        rbnCitaChef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnCitaChefActionPerformed(evt);
            }
        });

        buttonGroupCocina.add(rbnNoPrecisa);
        rbnNoPrecisa.setText("No precisa");
        rbnNoPrecisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnNoPrecisaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDatosEventoCocinaLayout = new javax.swing.GroupLayout(pnlDatosEventoCocina);
        pnlDatosEventoCocina.setLayout(pnlDatosEventoCocinaLayout);
        pnlDatosEventoCocinaLayout.setHorizontalGroup(
            pnlDatosEventoCocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosEventoCocinaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(rbnCarta)
                .addGap(27, 27, 27)
                .addComponent(rbnBufe, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rbnCitaChef, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbnNoPrecisa, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDatosEventoCocinaLayout.setVerticalGroup(
            pnlDatosEventoCocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosEventoCocinaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosEventoCocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(rbnCarta)
                    .addComponent(rbnBufe)
                    .addComponent(rbnCitaChef)
                    .addComponent(rbnNoPrecisa))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        btnReservar.setText("RESERVAR");
        btnReservar.setToolTipText("Realizar la reserva. Una vez realizada, se cierra el formulario");
        btnReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservarActionPerformed(evt);
            }
        });

        btnCancelar.setText("CANCELAR");
        btnCancelar.setToolTipText("Se elimina la reserva");

        btnReservarSinCierre.setText("RESERVAR(sin cierre)");
        btnReservarSinCierre.setToolTipText("Realizar la reserva (una vez realizada no se cierra el formulario)");

        javax.swing.GroupLayout pnlDatosEventoLayout = new javax.swing.GroupLayout(pnlDatosEvento);
        pnlDatosEvento.setLayout(pnlDatosEventoLayout);
        pnlDatosEventoLayout.setHorizontalGroup(
            pnlDatosEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosEventoLayout.createSequentialGroup()
                .addGroup(pnlDatosEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDatosEventoCocina, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlDatosEventoFechaAsistentes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlDatosEventoTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosEventoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnReservarSinCierre)
                .addGap(18, 18, 18)
                .addComponent(btnReservar)
                .addGap(29, 29, 29)
                .addComponent(btnCancelar)
                .addGap(66, 66, 66))
        );
        pnlDatosEventoLayout.setVerticalGroup(
            pnlDatosEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosEventoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDatosEventoFechaAsistentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlDatosEventoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlDatosEventoCocina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(pnlDatosEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReservar)
                    .addComponent(btnCancelar)
                    .addComponent(btnReservarSinCierre))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlDatosEvento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPersonaContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPersonaContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(pnlDatosEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtNumeroAsistentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroAsistentesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroAsistentesActionPerformed

    private void rBtnJornadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnJornadaActionPerformed
        // TODO add your handling code here:
        if(rBtnJornada.isSelected()){ /*si el boton esta seleccionado*/ 
            spinnerNumeroJornadas.setVisible(false);
            lblNumeroJornadas.setVisible(false);
            chkBRequiereHabitaciones.setVisible(false);
        }
    }//GEN-LAST:event_rBtnJornadaActionPerformed

    private void chkBRequiereHabitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBRequiereHabitacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkBRequiereHabitacionesActionPerformed

    private void rbnBufeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnBufeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnBufeActionPerformed

    private void rbnNoPrecisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnNoPrecisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnNoPrecisaActionPerformed

    private void rBtnBanqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnBanqueteActionPerformed
        // TODO add your handling code here:
        if(rBtnBanquete.isSelected()){ /*si el boton esta seleccionado*/ 
            spinnerNumeroJornadas.setVisible(false);
            lblNumeroJornadas.setVisible(false);
            chkBRequiereHabitaciones.setVisible(false);
        }
    }//GEN-LAST:event_rBtnBanqueteActionPerformed

    private void rBtnCongresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnCongresoActionPerformed
        // TODO add your handling code here:
        if(rBtnCongreso.isSelected()){ /*si el boton esta seleccionado*/ 
            spinnerNumeroJornadas.setVisible(true);
            lblNumeroJornadas.setVisible(true);
            chkBRequiereHabitaciones.setVisible(true);
        }
    }//GEN-LAST:event_rBtnCongresoActionPerformed

    private void rbnCitaChefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnCitaChefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnCitaChefActionPerformed

    private void btnReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReservarActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnReservar;
    public javax.swing.JButton btnReservarSinCierre;
    public javax.swing.ButtonGroup buttonGroupCocina;
    public javax.swing.ButtonGroup buttonGroupTipoEvento;
    public javax.swing.JCheckBox chkBRequiereHabitaciones;
    public com.toedter.calendar.JDateChooser dateChooserFecha;
    public javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNumeroAsistentes;
    private javax.swing.JLabel lblNumeroJornadas;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JPanel pnlDatosEvento;
    private javax.swing.JPanel pnlDatosEventoCocina;
    private javax.swing.JPanel pnlDatosEventoFechaAsistentes;
    private javax.swing.JPanel pnlDatosEventoTipo;
    private javax.swing.JPanel pnlPersonaContacto;
    public javax.swing.JRadioButton rBtnBanquete;
    public javax.swing.JRadioButton rBtnCongreso;
    private javax.swing.JRadioButton rBtnJornada;
    private javax.swing.JRadioButton rbnBufe;
    public javax.swing.JRadioButton rbnCarta;
    private javax.swing.JRadioButton rbnCitaChef;
    private javax.swing.JRadioButton rbnNoPrecisa;
    public javax.swing.JSpinner spinnerNumeroJornadas;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtNumeroAsistentes;
    public javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
