/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JDialog;

/**
 *
 * @author Angel FV
 */
public class ReservasJFramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Reservas
     */
    public ReservasJFramePrincipal() {
        Color backgroundColor = new Color(250, 250, 240);  //blanco roto
        getContentPane().setBackground(backgroundColor);
        initComponents();
        
        // Cambiar la fuente y el tamaño del texto en los JMenuItems
        Font customFont = new Font("Courier New", Font.BOLD, 18); // Fuente personalizada

        opcMenuSalones.setFont(customFont);
        opcMenuReservas.setFont(customFont);
        opcMenuOtras.setFont(customFont);
        opcMenuSalonesConsultar.setFont(customFont);
        opcMenuReservasAltas.setFont(customFont);
        opcMenuOtrasAcercaDe.setFont(customFont);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBGestionHotelera = new javax.swing.JMenuBar();
        opcMenuSalones = new javax.swing.JMenu();
        opcMenuSalonesConsultar = new javax.swing.JMenuItem();
        opcMenuReservas = new javax.swing.JMenu();
        opcMenuReservasAltas = new javax.swing.JMenuItem();
        opcMenuOtras = new javax.swing.JMenu();
        opcMenuOtrasAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        opcMenuSalones.setText("Salones");
        opcMenuSalones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcMenuSalonesActionPerformed(evt);
            }
        });

        opcMenuSalonesConsultar.setText("Consultar Salones");
        opcMenuSalonesConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcMenuSalonesConsultarActionPerformed(evt);
            }
        });
        opcMenuSalones.add(opcMenuSalonesConsultar);

        menuBGestionHotelera.add(opcMenuSalones);

        opcMenuReservas.setText("Reservas");

        opcMenuReservasAltas.setText("Nueva Reserva Salón Habana");
        opcMenuReservasAltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcMenuReservasAltasActionPerformed(evt);
            }
        });
        opcMenuReservas.add(opcMenuReservasAltas);

        menuBGestionHotelera.add(opcMenuReservas);

        opcMenuOtras.setText("Otras");
        opcMenuOtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcMenuOtrasActionPerformed(evt);
            }
        });

        opcMenuOtrasAcercaDe.setText("Acerca De");
        opcMenuOtras.add(opcMenuOtrasAcercaDe);

        menuBGestionHotelera.add(opcMenuOtras);

        setJMenuBar(menuBGestionHotelera);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 497, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opcMenuReservasAltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcMenuReservasAltasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcMenuReservasAltasActionPerformed

    private void opcMenuSalonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcMenuSalonesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcMenuSalonesActionPerformed

    private void opcMenuOtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcMenuOtrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcMenuOtrasActionPerformed

    private void opcMenuSalonesConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcMenuSalonesConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcMenuSalonesConsultarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar menuBGestionHotelera;
    private javax.swing.JMenu opcMenuOtras;
    public javax.swing.JMenuItem opcMenuOtrasAcercaDe;
    private javax.swing.JMenu opcMenuReservas;
    public javax.swing.JMenuItem opcMenuReservasAltas;
    public javax.swing.JMenu opcMenuSalones;
    public javax.swing.JMenuItem opcMenuSalonesConsultar;
    // End of variables declaration//GEN-END:variables
}
